def addition(x=10,y=20):
    print(f"預設1:{x}")
    print(f"預設2:{y}")
    print(f"相總:{x+y}")
a=int(input("請輸入第一個整數:"))
b=int(input("請輸入第二個整數:"))
print("您的數字相加為:")
addition(a,b)
print("預設數字為:")
addition()
print("您的第一個整數加預設2:")
addition(a)
print("您的第二個整數加預設2:")
addition(b)
print("輸入數值交換:")
addition(x=b,y=a)
